version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env.production
  user-service:
    build: ./user-service
    env_file: ./user-service/.env
  media-service:
    build: ./media-service
    env_file: ./media-service/.env
  post-service:
    build: ./post-service
    env_file: ./post-service/.env
