version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      USER_SERVICE_URL: http://user-service:3001
      POST_SERVICE_URL: http://post-service:3002
      MEDIA_SERVICE_URL: http://media-service:3004
    depends_on:
      - user-service
      - post-service
      - media-service

  user-service:
    build: ./user-service
    environment:
      PORT: 3001

  post-service:
    build: ./post-service
    environment:
      PORT: 3002

  media-service:
    build: ./media-service
    environment:
      PORT: 3004
